---
categories: [""]
date: 2022-08-11
title: "Best Quotes"
# weight: 1
# aliases: ["/first"]
tags: ["first","third"]
author: "Me"
showToc: true
TocOpen: false
draft: false
hidemeta: false
comments: false
description: "Desc Text."
canonicalURL: "https://canonical.url/to/page"
disableHLJS: true # to disable highlightjs
disableShare: false
disableHLJS: false
hideSummary: false
searchHidden: false
ShowReadingTime: true
ShowBreadCrumbs: true
ShowPostNavLinks: true
ShowWordCount: true
ShowRssButtonInSectionTermList: true
UseHugoToc: true
cover:
    image: "<image path/url>" # image path/url
    alt: "<alt text>" # alt text
    caption: "<text>" # display caption under cover
    relative: false # when using page bundles set this to true
    hidden: true # only hide on current single page

---

* Life
** Whatever is begun in anger ends in shame
** Life's biggest tragedy is that we get old too soon , and wise too late.
** Three faithful friends
1. Old wife
2. old dog
3. ready money
** No gains without pain
** Be careful about little expenses , a small lick will sink a great ship.
** He who displays his wallet and wife quite often , is in danger of having both of them borrowed.
** Never get attached to anything in life Friends, family, Pride, Success, Love, Material, Fame.
** expect the worst from the life , You will not be disappointed .
** Don't buy materialistic goods for show off , people should acknowledge you for your worth not for your fancy car or gadgets.
** Don't think of life like a constant struggle , =Hustle= but make sure you analyze and find ways  to automate the tasks or make them more fun and easy .

* Freedom
** Being discipline is the key to freedom.

* Hard Work
** hard work does not mean
you going to school regularly, or doing homework or not watching cartoon in the television,
That's the work everyone is doing . Hard work means after coming from school without opening up your phone you open your book and give a mock test.
when everyone is using social media you are going through previous year questions, when everyone is watching anime you are making notes and revision material for your upcoming exam .

* Truth
** Most of the time people take advantage of you saying you are better then them in something.
** Better not reading a book , Than trusting a book completely.
