---
categories: ["education"]
date: 2022-08-12
title: "Common Medical Preparation Mistakes to Avoid"
tags: ["second_time","medical","mistake","preparation"]
author: "Me"
showToc: true
TocOpen: false
draft: false
hidemeta: false
comments: false
description: "Some common mistake that students make during their first time mat exam."
canonicalURL: "https://canonical.url/to/page"
disableShare: false
disableHLJS: false
hideSummary: false
searchHidden: false
ShowReadingTime: true
ShowBreadCrumbs: true
ShowPostNavLinks: true
ShowWordCount: true
ShowRssButtonInSectionTermList: true
UseHugoToc: true
cover:
    image: "<image path/url>" # image path/url
    alt: "Image not available" # alt text
    caption: "<text>" # display caption under cover
    relative: false # when using page bundles set this to true
    hidden: false # only hide on current single page

---



* Main book er mcq pori nai , Unnecessary coaching material porsi
 Exam er maximum question come from main book itself.


* Exam hall e dhilami disi
 Wasting a single second in exam hall means dead. Carefull with roll number and serial number.


* English Gk beshi pori nai , vul jayga theke porsi
 ENglish is very importent , start english from the very begining.


* ROyal guide pori nai
 It is called the bible of medical.

* Previous year ==Medical== ar ==versity== question pori nai.
 Previous year *Board* *Versity* and medical dental question are very importent.


* Proper guidence er teacher nei nai.
 Anyone who is not a medical person can not give tips for this great exxam.


* Seser din gulate dhilami disi .
 Ran out of energy the last month or last 10 days , you are scrued .


* sort syllebus e gurutto  dei nai.
 wasn't carefull enough about the useless ness of the government of the bangladesh.


* Physics kom porsi.
 physics seames easy but this is very dengerous.


* Mistake book , rivision material banai nai . Active recall Nates banai nai
 examer  age sara boi hatray beraite hoise er jonno


* 100/100 target rakhi nai.
 if you dont target high you wouldnt even get the low.


* Seser dike aisa distracted hoye gesi onek  besi.
 Last time is more importent. DOnt you dare ruen this time.


* Sudhu Knowladge gather korsi , exam/test er preperation nei nai.. enough exam dei nai.
 Exam can be done well if you practice giving exam more and more.
 get familiarized with this pain of exam.
